# SCRIPT 1: Parsing the local HTML file with BeautifulSoup
# ---------------------------------------------------------
# This script will parse the HTML file you provided.
# NOTE: It will find the container for the table, but the container will be
# empty because the table data is loaded by JavaScript, which doesn't run
# when you just parse a static HTML file.

from bs4 import BeautifulSoup
import datetime


def scrape_static_html(file_path):
    """
    Parses a static HTML file and looks for the leaderboard table.
    """
    print("--- Running Script 1: Parsing static HTML file ---")
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            html_content = f.read()

        soup = BeautifulSoup(html_content, 'html.parser')

        # The table is generated inside a div with the id 'leaderboard-table'
        table_container = soup.find('div', id='leaderboard-table')

        if table_container:
            # We look for a 'table' element inside the container
            table = table_container.find('table')
            if table:
                print("Successfully found the table in the static file.")
                # (Add table processing logic here if it existed in the static file)
            else:
                print("Found the 'leaderboard-table' div, but it's empty.")
                print("This is expected because the table is generated by JavaScript after the page loads.")
        else:
            print("Could not find the 'leaderboard-table' div in the HTML.")

    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")
    print("-" * 50)


# SCRIPT 2: Scraping the live website with Selenium and BeautifulSoup
# --------------------------------------------------------------------
# This is the recommended script for your task. It automates a web browser
# to load the page, waits for the JavaScript to generate the table,
# and then scrapes the data, saving it to a CSV file.

# Prerequisites:
# You will need to install selenium, pandas, and a webdriver.
# 1. Install libraries:
#    pip install selenium pandas beautifulsoup4 webdriver-manager
#
# 2. The webdriver-manager will automatically download the correct driver
#    for your installed version of Chrome.

import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

def scrape_live_website(url):
    """
    Scrapes the dynamically generated leaderboard table from the live website.
    """
    print("\n--- Running Script 2: Scraping the live website ---")
    try:
        # Set up Chrome options for headless mode (optional)
        chrome_options = webdriver.ChromeOptions()
        # chrome_options.add_argument("--headless") # Run without opening a browser window
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")

        # Initialize the Chrome driver
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=chrome_options)

        print(f"Navigating to {url}...")
        driver.get(url)

        # Wait for the table to be present in the DOM.
        # We wait for the 'table' element inside the 'leaderboard-table' div.
        # This is the crucial step to handle dynamic content.
        print("Waiting for the leaderboard table to load...")
        
        wait = WebDriverWait(driver, 20) # Wait up to 20 seconds
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#leaderboard-table table")))
        print("Table loaded successfully.")

        # Get the page source after JavaScript has executed
        html_content = driver.page_source

        # Parse the rendered HTML with BeautifulSoup
        soup = BeautifulSoup(html_content, 'html.parser')
        table = soup.select_one("#leaderboard-table table")

        # Extract data into a pandas DataFrame
        if table:
            df = pd.read_html(str(table))[0]

            # Data Cleaning (example: remove unnamed columns if they appear)
            df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

            print("\nScraped Data Preview:")
            print(df.head())

            # Save the DataFrame to a CSV file
            current_date = datetime.datetime.now().strftime("%Y%m%d")
            output_filename = 'benchmarks/arc_{}.csv'.format(current_date)
            df.to_csv(output_filename, index=False)
            print(f"\nSuccessfully saved the data to '{output_filename}'")
        else:
            print("Error: Could not find the table even after waiting.")

    except Exception as e:
        print(f"An error occurred during live scraping: {e}")
    finally:
        if 'driver' in locals():
            driver.quit()
            print("Browser closed.")


if __name__ == '__main__':
    # --- Part 1: Run the script on the local file ---
    # Replace with the actual path to your downloaded HTML file
    local_html_file = 'ARC Prize - Leaderboard.html'
    scrape_static_html(local_html_file)

    # --- Part 2: Run the script on the live website ---
    live_url = 'https://arcprize.org/leaderboard'
    scrape_live_website(live_url)